// Auto-generated bundled dataset for Vercel Serverless environment
module.exports = {
  device: [
  {
    "asset_code": "N1C102",
    "asset_name": "Packing_set_room",
    "holder": "หน้าห้องแต่งตัวลูกค้า",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463423",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.11",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "48.3900",
    "y": "38.5000"
  },
  {
    "asset_code": "N3C602",
    "asset_name": "peel_line_2",
    "holder": "รีดเม็ด ผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8234245",
    "department": "2ผลิต",
    "ip": "192.168.20.48",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "75.6600",
    "y": "24.0400"
  },
  {
    "asset_code": "N1C702",
    "asset_name": "costume",
    "holder": "โรงเก็บผ้า",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463414",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.8",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "45.6600",
    "y": "16.0800"
  },
  {
    "asset_code": "N4C902",
    "asset_name": "Load_ST",
    "holder": "ช่องโหลด",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.89",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "66.9700",
    "y": "50.7300"
  },
  {
    "asset_code": "N4C1502",
    "asset_name": "locker_PA",
    "holder": "ล๊อกเกอร์ แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.90",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.2200",
    "y": "43.4100"
  },
  {
    "asset_code": "PR58",
    "asset_name": "CM1-PR58",
    "holder": "PR58",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "71.1200",
    "y": "59.5300"
  },
  {
    "asset_code": "OS09",
    "asset_name": "CM1-OS09",
    "holder": "OS09",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "64.8500",
    "y": "15.8500"
  },
  {
    "asset_code": "N4C1302",
    "asset_name": "basket_clean",
    "holder": "ลานล้างตระกร้า",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.73",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "78.5100",
    "y": "23.3400"
  },
  {
    "asset_code": "N1C2902",
    "asset_name": "ST_dry_front",
    "holder": "หน้าสโตร์แห้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20231201AAWRAX3842231",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.56",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "39.3500",
    "y": "18.4500"
  },
  {
    "asset_code": "N4C1002",
    "asset_name": "locker_PR",
    "holder": "ห้องเก็บของผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.74",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "77.4300",
    "y": "33.3100"
  },
  {
    "asset_code": "N1C1502",
    "asset_name": "load_new",
    "holder": "ทางขึ้น โรงใหม่",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "20240715AAWRFH4748685",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.68",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.5000",
    "y": "85.8500"
  },
  {
    "asset_code": "N2C1202",
    "asset_name": "Auto_A",
    "holder": "Auto A",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929375",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.41",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.8500",
    "y": "34.6900"
  },
  {
    "asset_code": "CONNETTA52",
    "asset_name": "CM1-CONNETTA52",
    "holder": "CONNETTA52",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "91.3300",
    "y": "37.1300"
  },
  {
    "asset_code": "N3C1102",
    "asset_name": "Cutter_line_2",
    "holder": "Cutter line 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8234242",
    "department": "2ผลิต",
    "ip": "192.168.20.47",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "69.9100",
    "y": "25.1500"
  },
  {
    "asset_code": "PA32",
    "asset_name": "CM1-PA32",
    "holder": "PA32",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.2800",
    "y": "45.1100"
  },
  {
    "asset_code": "RM60",
    "asset_name": "CM1-RM60",
    "holder": "RM60",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "86.4700",
    "y": "20.0000"
  },
  {
    "asset_code": "N4C2302",
    "asset_name": "Bean_gliding",
    "holder": "ร่อนถั่ว ผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.94",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "54.1500",
    "y": "29.4900"
  },
  {
    "asset_code": "N4C2202",
    "asset_name": "select_PR_line_2",
    "holder": "เครื่องคัด ไลน์ 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.98",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "65.4200",
    "y": "29.7400"
  },
  {
    "asset_code": "ST16",
    "asset_name": "CM1-ST16",
    "holder": "ST16",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.5900",
    "y": "29.5700"
  },
  {
    "asset_code": "N3C1202",
    "asset_name": "chemical_PA",
    "holder": "ห้องสารเคมี แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231201AAWRAX3842245",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.62",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "48.7800",
    "y": "34.2300"
  },
  {
    "asset_code": "PA37",
    "asset_name": "CM1-PA37",
    "holder": "PA37",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "36.1700",
    "y": "40.5900"
  },
  {
    "asset_code": "OS01",
    "asset_name": "CM1-OS01",
    "holder": "OS01",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "28.8900",
    "y": "12.9900"
  },
  {
    "asset_code": "N1C3002",
    "asset_name": "Newload_E",
    "holder": "ลานห้องเย็นใหม่ ตะวันออก",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "20240715AAWRFH4748623",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.67",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "55.4800",
    "y": "79.2300"
  },
  {
    "asset_code": "N4C602",
    "asset_name": "CD2",
    "holder": "ห้องเย็น 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.86",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "54.3600",
    "y": "44.7900"
  },
  {
    "asset_code": "N3C702",
    "asset_name": "larn_RM",
    "holder": "ลานรับวัตถุดิบ",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8234397",
    "department": "2รับวัตถุดิบ",
    "ip": "192.168.20.49",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "71.6400",
    "y": "37.0300"
  },
  {
    "asset_code": "N1C1302",
    "asset_name": "Motorcycle_garage",
    "holder": "โรงจอดรถ ตะวันตก",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2027G1-L",
    "serial": "L20201106AAWRF05200774",
    "department": "2บุคคลฯ",
    "ip": "192.168.0.214",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "23.1100",
    "y": "55.1500"
  },
  {
    "asset_code": "N1C402",
    "asset_name": "ExitDoor_Office",
    "holder": "ทางออกฉุกเฉิน สำนักงาน",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463381",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.5",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "4",
    "x": "72.7400",
    "y": "91.4900"
  },
  {
    "asset_code": "PR43",
    "asset_name": "CM1-PR43",
    "holder": "PR43",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "59.9500",
    "y": "45.8900"
  },
  {
    "asset_code": "N2C902",
    "asset_name": "Auto_D",
    "holder": "Auto D",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929293",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.38",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.2700",
    "y": "34.7300"
  },
  {
    "asset_code": "PA34",
    "asset_name": "CM1-PA34",
    "holder": "PA34",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "41.2900",
    "y": "58.9300"
  },
  {
    "asset_code": "CONNETTA50",
    "asset_name": "CM1-CONNETTA50",
    "holder": "CONNETTA50",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "91.4300",
    "y": "43.2400"
  },
  {
    "asset_code": "N3C902",
    "asset_name": "check_bag_GB",
    "holder": "เช็คถุง GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.63",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.3100",
    "y": "46.2400"
  },
  {
    "asset_code": "N3C802",
    "asset_name": "load_RM",
    "holder": "ช่องจอดรถ รับวัตถุดิบ",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "",
    "department": "2รับวัตถุดิบ",
    "ip": "192.168.20.53",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "72.2400",
    "y": "37.0300"
  },
  {
    "asset_code": "ST17",
    "asset_name": "CM1-ST17",
    "holder": "ST17",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "16.9000",
    "y": "96.5600"
  },
  {
    "asset_code": "N4C1402",
    "asset_name": "Water_tredment",
    "holder": "บ่อบำบัด",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สิ่งแวดล้อม",
    "ip": "192.168.20.72",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "79.2500",
    "y": "26.6500"
  },
  {
    "asset_code": "N1C1802",
    "asset_name": "FN_gb",
    "holder": "บรรจุกล่อง GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929376",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.19",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.6500",
    "y": "47.2500"
  },
  {
    "asset_code": "N1C1402",
    "asset_name": "Data_center",
    "holder": "ห้องกล้องวงจรปิด",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929272",
    "department": "2เทคโนโลยีสารสนเทศ",
    "ip": "192.168.20.42",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.1800",
    "y": "49.9500"
  },
  {
    "asset_code": "N4C402",
    "asset_name": "Larn_Load",
    "holder": "ลานโหลด",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617264",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.84",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "65.7400",
    "y": "50.6300"
  },
  {
    "asset_code": "N4C1802",
    "asset_name": "dress_room_PA",
    "holder": "ห้องแขวนชุด แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.92",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "48.4400",
    "y": "44.2000"
  },
  {
    "asset_code": "PR54",
    "asset_name": "CM1-PR54",
    "holder": "PR54",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "73.0000",
    "y": "31.6700"
  },
  {
    "asset_code": "N1C302",
    "asset_name": "Front_Office",
    "holder": "ประตูใหญ่ สำนักงาน",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463460",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.4",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.7300",
    "y": "56.2500"
  },
  {
    "asset_code": "RM68",
    "asset_name": "CM1-RM68",
    "holder": "RM68",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "98.6200",
    "y": "33.0100"
  },
  {
    "asset_code": "PR41",
    "asset_name": "CM1-PR41",
    "holder": "PR41",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "48.9600",
    "y": "43.7000"
  },
  {
    "asset_code": "N4C1902",
    "asset_name": "Control_MC",
    "holder": "ห้องควบคุม เครื่องกล",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2เครื่องกล",
    "ip": "192.168.20.97",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "65.1500",
    "y": "26.7300"
  },
  {
    "asset_code": "PA36",
    "asset_name": "CM1-PA36",
    "holder": "PA36",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "30.8500",
    "y": "36.2900"
  },
  {
    "asset_code": "PR71",
    "asset_name": "CM1-PR71",
    "holder": "PR71",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "CONNETTA49",
    "asset_name": "CM1-CONNETTA49",
    "holder": "CONNETTA49",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "89.7800",
    "y": "40.1900"
  },
  {
    "asset_code": "N3C102",
    "asset_name": "hand_wash_PR",
    "holder": "ล้างมือ ผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20231211AAWRAX8234354",
    "department": "2ผลิต",
    "ip": "192.168.20.57",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "76.8300",
    "y": "29.0700"
  },
  {
    "asset_code": "N1C2302",
    "asset_name": "Auto_detector",
    "holder": "ตรวจสอบโลหะ Auto",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929288",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.26",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.5300",
    "y": "32.9700"
  },
  {
    "asset_code": "ST46",
    "asset_name": "CM1-ST46",
    "holder": "ST46",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "14.2200",
    "y": "80.6500"
  },
  {
    "asset_code": "PA27",
    "asset_name": "CM1-PA27",
    "holder": "PA27",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "30.9800",
    "y": "58.8200"
  },
  {
    "asset_code": "MC63",
    "asset_name": "CM1-MC63",
    "holder": "MC63",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1เครื่องกล",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "55.1200",
    "y": "42.7400"
  },
  {
    "asset_code": "RM65",
    "asset_name": "CM1-RM65",
    "holder": "RM65",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "89.4000",
    "y": "20.7500"
  },
  {
    "asset_code": "OS08",
    "asset_name": "CM1-OS08",
    "holder": "OS08",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "15.2400",
    "y": "12.0000"
  },
  {
    "asset_code": "N1C502",
    "asset_name": "Nure_room",
    "holder": "หน้าห้องพยาบาล",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463457",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.6",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "46.4400",
    "y": "54.9200"
  },
  {
    "asset_code": "PA21",
    "asset_name": "CM1-PA21",
    "holder": "PA21",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "28.7500",
    "y": "59.1900"
  },
  {
    "asset_code": "N1C2102",
    "asset_name": "receive_SB",
    "holder": "บรรจุกล่อง SB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929300",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.23",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.5400",
    "y": "38.3700"
  },
  {
    "asset_code": "N1C202",
    "asset_name": "Packing_exit",
    "holder": "ทางออก แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463425",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.55",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.2200",
    "y": "42.1700"
  },
  {
    "asset_code": "N4C102",
    "asset_name": "CD3",
    "holder": "ห้องเย็น 3",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617272",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.81",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "54.3600",
    "y": "46.8900"
  },
  {
    "asset_code": "OS11",
    "asset_name": "CM1-OS11",
    "holder": "OS11",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "17.3100",
    "y": "39.1200"
  },
  {
    "asset_code": "OS04",
    "asset_name": "CM1-OS04",
    "holder": "OS04",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "4.1400",
    "y": "12.3900"
  },
  {
    "asset_code": "OS05",
    "asset_name": "CM1-OS05",
    "holder": "OS05",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "10.1400",
    "y": "20.3500"
  },
  {
    "asset_code": "N1C2202",
    "asset_name": "Cabitnet_PA",
    "holder": "ห้องเก็บของ แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929294",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.25",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.7600",
    "y": "35.1200"
  },
  {
    "asset_code": "PA23",
    "asset_name": "CM1-PA23",
    "holder": "PA23",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "35.5800",
    "y": "32.3100"
  },
  {
    "asset_code": "PR57",
    "asset_name": "CM1-PR57",
    "holder": "PR57",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "89.5100",
    "y": "14.3700"
  },
  {
    "asset_code": "N2C1702",
    "asset_name": "Fastback_Auto1",
    "holder": "รางลำเลียง Auto1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2026G2-I",
    "serial": "I20201216AAWRF21488682",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.15",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.4100",
    "y": "34.4300"
  },
  {
    "asset_code": "PR70",
    "asset_name": "CM1-PR70",
    "holder": "PR70",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "RM67",
    "asset_name": "CM1-RM67",
    "holder": "RM67",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "PA24",
    "asset_name": "CM1-PA24",
    "holder": "PA24",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "30.9500",
    "y": "43.8300"
  },
  {
    "asset_code": "N1C2002",
    "asset_name": "SB_select",
    "holder": "สายพานรวม SB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929275",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.22",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.5600",
    "y": "36.8300"
  },
  {
    "asset_code": "N2C802",
    "asset_name": "Auto_AB",
    "holder": "Auto AB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230824AAWRAF6298033",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.37",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "51.9400",
    "y": "36.5500"
  },
  {
    "asset_code": "N2C602",
    "asset_name": "Fastback_auto2",
    "holder": "รางลำเลียง Auto2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929276",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.35",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.7500",
    "y": "34.3100"
  },
  {
    "asset_code": "N1C602",
    "asset_name": "Side_Office",
    "holder": "ประตูข้าง สำนักงาน",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463436",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.7",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "46.4300",
    "y": "54.5800"
  },
  {
    "asset_code": "D4C202",
    "asset_name": "Bio2",
    "holder": "ห้องเตรียมสาร Lab",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ห้องปฏิบัติการ",
    "ip": "192.168.20.204",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "4",
    "x": "12.3400",
    "y": "12.2600"
  },
  {
    "asset_code": "OS14",
    "asset_name": "CM1-OS14",
    "holder": "OS14",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "12.3700",
    "y": "78.5700"
  },
  {
    "asset_code": "OS06",
    "asset_name": "CM1-OS06",
    "holder": "OS06",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "3.2300",
    "y": "12.4300"
  },
  {
    "asset_code": "N3C1302",
    "asset_name": "F1_PA",
    "holder": "ห้องกล่อง แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231201AAWRAX3842227",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.61",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.9100",
    "y": "33.4400"
  },
  {
    "asset_code": "ST47",
    "asset_name": "CM1-ST47",
    "holder": "ST47",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "19.5000",
    "y": "96.0300"
  },
  {
    "asset_code": "N1C1002",
    "asset_name": "workway_door",
    "holder": "ประตูทางเข้า เล็ก",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2027G1-L",
    "serial": "L20201106AAWRF05200742",
    "department": "2บุคคลฯ",
    "ip": "192.168.0.211",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "16.8000",
    "y": "55.1300"
  },
  {
    "asset_code": "OS20",
    "asset_name": "CM1-OS20",
    "holder": "OS20",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "26.3400",
    "y": "31.5200"
  },
  {
    "asset_code": "OS07",
    "asset_name": "CM1-OS07",
    "holder": "OS07",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "12.4000",
    "y": "11.2200"
  },
  {
    "asset_code": "PA35",
    "asset_name": "CM1-PA35",
    "holder": "PA35",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "34.0400",
    "y": "40.1600"
  },
  {
    "asset_code": "N4C2102",
    "asset_name": "Larn_MC",
    "holder": "ลาน เครื่องกล",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2เครื่องกล",
    "ip": "192.168.20.96",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "66.6700",
    "y": "23.8700"
  },
  {
    "asset_code": "N2C402",
    "asset_name": "IQF_line1",
    "holder": "IQF line 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929319",
    "department": "2ผลิต",
    "ip": "192.168.20.33",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "56.8000",
    "y": "29.3200"
  },
  {
    "asset_code": "OS03",
    "asset_name": "CM1-OS03",
    "holder": "OS03",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "3.5900",
    "y": "24.5300"
  },
  {
    "asset_code": "N1C1102",
    "asset_name": "Big_Factory_Gate",
    "holder": "ประตูทางเข้า ใหญ่",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2027G1-L",
    "serial": "L20201106AAWRF05200760",
    "department": "2บุคคลฯ",
    "ip": "192.168.0.212",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "17.0800",
    "y": "58.1100"
  },
  {
    "asset_code": "ST10",
    "asset_name": "CM1-ST10",
    "holder": "ST10",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "20.4700",
    "y": "80.0000"
  },
  {
    "asset_code": "N2C1302",
    "asset_name": "GB_1",
    "holder": "โต๊ะคัด 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929262",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.43",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.6100",
    "y": "46.6100"
  },
  {
    "asset_code": "N3C1602",
    "asset_name": "Water_Tank",
    "holder": "บ่อบาดาล",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8219180",
    "department": "2เครื่องกล",
    "ip": "192.168.20.64",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "44.5900",
    "y": "27.2400"
  },
  {
    "asset_code": "D4C102",
    "asset_name": "Chem2",
    "holder": "ห้องสกัดสาร Lab",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ห้องปฏิบัติการ",
    "ip": "192.168.20.204",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "4",
    "x": "24.0800",
    "y": "79.2300"
  },
  {
    "asset_code": "N2C1402",
    "asset_name": "GB_4",
    "holder": "โต๊ะคัด 4",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929227",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.44",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.5800",
    "y": "42.0400"
  },
  {
    "asset_code": "N2C502",
    "asset_name": "Salt_storage",
    "holder": "โรงเก็บเกลือ",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929270",
    "department": "2ผลิต",
    "ip": "192.168.20.34",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.1100",
    "y": "18.0300"
  },
  {
    "asset_code": "PR56",
    "asset_name": "CM1-PR56",
    "holder": "PR56",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "74.8100",
    "y": "32.2600"
  },
  {
    "asset_code": "N1C2602",
    "asset_name": "Salt_tank_line",
    "holder": "ถังเกลือ ไลน์ 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617235",
    "department": "2ผลิต",
    "ip": "192.168.20.29",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "60.0000",
    "y": "29.9600"
  },
  {
    "asset_code": "N4C502",
    "asset_name": "CD1",
    "holder": "ห้องเย็น 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617282",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.85",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "54.0800",
    "y": "36.7900"
  },
  {
    "asset_code": "N4C2002",
    "asset_name": "F1_PR",
    "holder": "ห้องกล่อง ผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.95",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "56.7300",
    "y": "27.9100"
  },
  {
    "asset_code": "N2C702",
    "asset_name": "Auto_CD",
    "holder": "Auto CD",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20230712AAWRAD6929294",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.36",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "52.3400",
    "y": "36.5900"
  },
  {
    "asset_code": "N3C202",
    "asset_name": "Chill_room",
    "holder": "ห้องชิล รับวัตถุดิบ",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20231211AAWRAX8234253",
    "department": "2รับวัตถุดิบ",
    "ip": "192.168.20.58",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "65.8900",
    "y": "40.3300"
  },
  {
    "asset_code": "PA26",
    "asset_name": "CM1-PA26",
    "holder": "PA26",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.0800",
    "y": "40.7700"
  },
  {
    "asset_code": "N1C1202",
    "asset_name": "Motorcycle_garage",
    "holder": "โรงจอดรถ ตะวันออก",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2027G1-L",
    "serial": "L20201106AAWRF05200745",
    "department": "2บุคคลฯ",
    "ip": "192.168.0.213",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "23.7400",
    "y": "55.1300"
  },
  {
    "asset_code": "N1C2402",
    "asset_name": "FN_auto",
    "holder": "บรรจุกล่อง Auto",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929307",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.27",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.6100",
    "y": "33.7300"
  },
  {
    "asset_code": "N1C802",
    "asset_name": "lonry_mac",
    "holder": "โรงซักผ้า",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20190118AAWRC89463512",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.9",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "46.1300",
    "y": "17.9700"
  },
  {
    "asset_code": "N1C902",
    "asset_name": "locker_room_pa",
    "holder": "ตู้ล๊อกเกอร์ แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD2025FWD-I",
    "serial": "I20200824AAWRE73014076",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.10",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.2700",
    "y": "41.1800"
  },
  {
    "asset_code": "C38.0960",
    "asset_name": "C38.0960",
    "holder": "คเชนทร์",
    "type": "UPS",
    "brand": "APC",
    "model": "800",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617274",
    "department": "2เทคโนโลยีสารสนเทศ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.5700",
    "y": "51.3200"
  },
  {
    "asset_code": "N1C1702",
    "asset_name": "GB_detector",
    "holder": "ตรวจสอบโลหะ GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929273",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.18",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.4900",
    "y": "50.7500"
  },
  {
    "asset_code": "CONNETTA51",
    "asset_name": "CM1-CONNETTA51",
    "holder": "CONNETTA51",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "88.7600",
    "y": "49.2300"
  },
  {
    "asset_code": "N1C1902",
    "asset_name": "receive_GB",
    "holder": "ตกเกรด GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929353",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.23",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "52.0700",
    "y": "41.6200"
  },
  {
    "asset_code": "N4C1702",
    "asset_name": "font_packing",
    "holder": "ถนนหน้า แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.91",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "46.3800",
    "y": "48.0200"
  },
  {
    "asset_code": "PR72",
    "asset_name": "CM1-PR72",
    "holder": "PR72",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "D4C402",
    "asset_name": "Chem1",
    "holder": "ห้องเขี่ยเชื้อ Lab",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ห้องปฏิบัติการ",
    "ip": "192.168.20.204",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "4",
    "x": "26.8300",
    "y": "79.3400"
  },
  {
    "asset_code": "N2C1802",
    "asset_name": "Auto_F",
    "holder": "Auto F",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD1023G2-LIU",
    "serial": "DS-2CD1023G2-LIU20251117AAWRGK8163825",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.12",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.8200",
    "y": "34.7500"
  },
  {
    "asset_code": "ST18",
    "asset_name": "CM1-ST18",
    "holder": "ST18",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "12.1900",
    "y": "85.8100"
  },
  {
    "asset_code": "PA30",
    "asset_name": "CM1-PA30",
    "holder": "PA30",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.3100",
    "y": "58.9400"
  },
  {
    "asset_code": "N1C3102",
    "asset_name": "Newload_W",
    "holder": "ลานห้องเย็นใหม่ ตะวันตก",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "20240715AAWRFH4748741",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.69",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "35.8500",
    "y": "76.5500"
  },
  {
    "asset_code": "N2C1102",
    "asset_name": "Auto_B",
    "holder": "Auto B",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929384",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.40",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "51.4200",
    "y": "34.6700"
  },
  {
    "asset_code": "OS12",
    "asset_name": "CM1-OS12",
    "holder": "OS12",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "20.8500",
    "y": "59.0100"
  },
  {
    "asset_code": "RM66",
    "asset_name": "CM1-RM66",
    "holder": "RM66",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "64.7800",
    "y": "23.1200"
  },
  {
    "asset_code": "N1C3202",
    "asset_name": "New_engine_room",
    "holder": "ห้องเครื่อง โรงใหม่",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD1023G0E-I",
    "serial": "I20210228AAWRF59489439",
    "department": "2เครื่องกล",
    "ip": "192.168.20.70",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "57.9900",
    "y": "72.9900"
  },
  {
    "asset_code": "N1C2702",
    "asset_name": "PA_hand-wash",
    "holder": "ล้างมือ แพคกิ้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929346",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.24",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "49.8600",
    "y": "36.9100"
  },
  {
    "asset_code": "PR45",
    "asset_name": "CM1-PR45",
    "holder": "PR45",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "PR53",
    "asset_name": "CM1-PR53",
    "holder": "PR53",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "",
    "y": ""
  },
  {
    "asset_code": "N3C1402",
    "asset_name": "Check_bag_auto",
    "holder": "เช็คถุง Auto",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231201AAWRAX3842250",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.60",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.4800",
    "y": "45.2700"
  },
  {
    "asset_code": "PR44",
    "asset_name": "CM1-PR44",
    "holder": "PR44",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "42.6200",
    "y": "43.5600"
  },
  {
    "asset_code": "OS13",
    "asset_name": "CM1-OS13",
    "holder": "OS13",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "4.8100",
    "y": "78.4400"
  },
  {
    "asset_code": "N3C1002",
    "asset_name": "larn_PR",
    "holder": "ลานผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8234351",
    "department": "2ผลิต",
    "ip": "192.168.20.52",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "75.5900",
    "y": "36.1800"
  },
  {
    "asset_code": "N2C1002",
    "asset_name": "Auto_C",
    "holder": "Auto C",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929319",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.39",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "52.4600",
    "y": "34.7100"
  },
  {
    "asset_code": "N3C1502",
    "asset_name": "Y_way_STL",
    "holder": "3 แยก บ่อบาดาล",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8219184",
    "department": "2เครื่องกล",
    "ip": "192.168.20.65",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.0700",
    "y": "22.4100"
  },
  {
    "asset_code": "N2C1502",
    "asset_name": "Seal",
    "holder": "ซิล GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929374",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.45",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.5100",
    "y": "46.8300"
  },
  {
    "asset_code": "PR40",
    "asset_name": "CM1-PR40",
    "holder": "PR40",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "58.7800",
    "y": "49.0700"
  },
  {
    "asset_code": "CONNETTA48",
    "asset_name": "CM1-CONNETTA48",
    "holder": "CONNETTA48",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "85.2700",
    "y": "44.5200"
  },
  {
    "asset_code": "N2C1602",
    "asset_name": "GB_Weightier",
    "holder": "ชั่ง GB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929377",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.46",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.5500",
    "y": "42.1400"
  },
  {
    "asset_code": "RM61",
    "asset_name": "CM1-RM61",
    "holder": "RM61",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "87.5700",
    "y": "20.3200"
  },
  {
    "asset_code": "C38.0761",
    "asset_name": "C38.0761",
    "holder": "คเชนทร์",
    "type": "UPS",
    "brand": "APC",
    "model": "800",
    "serial": "DS-2CD3021G0-I20240821AAWRFM4617258",
    "department": "2เทคโนโลยีสารสนเทศ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "53.8400",
    "y": "51.3300"
  },
  {
    "asset_code": "RM69",
    "asset_name": "CM1-RM69",
    "holder": "RM69",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "99.1100",
    "y": "34.9500"
  },
  {
    "asset_code": "PA25",
    "asset_name": "CM1-PA25",
    "holder": "PA25",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "40.0100",
    "y": "33.0300"
  },
  {
    "asset_code": "PR55",
    "asset_name": "CM1-PR55",
    "holder": "PR55",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "72.1900",
    "y": "42.3300"
  },
  {
    "asset_code": "N4C1102",
    "asset_name": "Chemical_PR",
    "holder": "ห้องสารเคมีผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.75",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "78.6200",
    "y": "28.0300"
  },
  {
    "asset_code": "N3C402",
    "asset_name": "cutter_line_1",
    "holder": "สายพานไลน์ 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20231211AAWRAX8234345",
    "department": "2ผลิต",
    "ip": "192.168.20.51",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "69.6700",
    "y": "31.7700"
  },
  {
    "asset_code": "RM73",
    "asset_name": "CM1-RM73",
    "holder": "RM73",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "98.6600",
    "y": "58.6100"
  },
  {
    "asset_code": "ST15",
    "asset_name": "CM1-ST15",
    "holder": "ST15",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "20.8800",
    "y": "87.8500"
  },
  {
    "asset_code": "N4C702",
    "asset_name": "CD5",
    "holder": "ห้องเย็น 5",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.87",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "60.3500",
    "y": "40.3300"
  },
  {
    "asset_code": "N1C1602",
    "asset_name": "Dry_store_warehouse",
    "holder": "สโตร์แห้ง",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD1023G0E-I",
    "serial": "I20210228AAWRF59489513",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.17",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "38.7500",
    "y": "18.1800"
  },
  {
    "asset_code": "PR59",
    "asset_name": "CM1-PR59",
    "holder": "PR59",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "53.7600",
    "y": "58.9500"
  },
  {
    "asset_code": "ST19",
    "asset_name": "CM1-ST19",
    "holder": "ST19",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1สโตร์ฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "16.0400",
    "y": "77.1000"
  },
  {
    "asset_code": "N2C102",
    "asset_name": "Wash_line2",
    "holder": "ถังล้าง ไลน์ 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929269",
    "department": "2ผลิต",
    "ip": "192.168.20.30",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "63.2500",
    "y": "29.9400"
  },
  {
    "asset_code": "PR38",
    "asset_name": "CM1-PR38",
    "holder": "PR38",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "81.8600",
    "y": "37.9100"
  },
  {
    "asset_code": "D4C302",
    "asset_name": "Bio1",
    "holder": "ห้องเก็บเชื้อ Lab",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ห้องปฏิบัติการ",
    "ip": "192.168.20.204",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "4",
    "x": "14.8900",
    "y": "15.2100"
  },
  {
    "asset_code": "RM64",
    "asset_name": "CM1-RM64",
    "holder": "RM64",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "92.2000",
    "y": "23.2300"
  },
  {
    "asset_code": "RM39",
    "asset_name": "CM1-RM39",
    "holder": "RM39",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "96.3400",
    "y": "17.4200"
  },
  {
    "asset_code": "PR42",
    "asset_name": "CM1-PR42",
    "holder": "PR42",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1ผลิต",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "79.3500",
    "y": "63.3500"
  },
  {
    "asset_code": "OS02",
    "asset_name": "CM1-OS02",
    "holder": "OS02",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1บุคคลฯ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "30.7100",
    "y": "13.3300"
  },
  {
    "asset_code": "N2C302",
    "asset_name": "IQF_line2",
    "holder": "IQF line 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929370",
    "department": "2ผลิต",
    "ip": "192.168.20.32",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "56.7400",
    "y": "32.6200"
  },
  {
    "asset_code": "N1C2502",
    "asset_name": "Shaker_line",
    "holder": "ถังเกลือ ไลน์ 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929289",
    "department": "2ผลิต",
    "ip": "192.168.20.28",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "59.9800",
    "y": "31.6800"
  },
  {
    "asset_code": "N3C502",
    "asset_name": "cutter_line_2",
    "holder": "สายพานลำเลียงไลน์ 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "DS-2CD3021G0-I20231211AAWRAX8234269",
    "department": "2ผลิต",
    "ip": "192.168.20.59",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "69.7300",
    "y": "36.4300"
  },
  {
    "asset_code": "N2C202",
    "asset_name": "wash_line1",
    "holder": "ถังล้าง ไลน์ 1",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929359",
    "department": "2ผลิต",
    "ip": "192.168.20.31",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "63.1800",
    "y": "31.7200"
  },
  {
    "asset_code": "N4C1602",
    "asset_name": "Attendent_time",
    "holder": "ลานรูดบัตร",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2บุคคลฯ",
    "ip": "192.168.20.93",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "44.6300",
    "y": "49.0200"
  },
  {
    "asset_code": "N4C1202",
    "asset_name": "dress_room_PR",
    "holder": "ตู้ล๊อกเกอร์ผลิต",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2ผลิต",
    "ip": "192.168.20.71",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "78.4500",
    "y": "29.0700"
  },
  {
    "asset_code": "N1C2802",
    "asset_name": "SB_shaker",
    "holder": "รางลำเลียง SB",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20230712AAWRAD6929301",
    "department": "2แพคกิ้ง",
    "ip": "192.168.20.21",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "50.5600",
    "y": "40.3100"
  },
  {
    "asset_code": "PA33",
    "asset_name": "CM1-PA33",
    "holder": "PA33",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "39.9500",
    "y": "45.0000"
  },
  {
    "asset_code": "PA22",
    "asset_name": "CM1-PA22",
    "holder": "PA22",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "34.2500",
    "y": "33.2400"
  },
  {
    "asset_code": "N4C802",
    "asset_name": "CD11",
    "holder": "ห้องเย็น 11",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.88",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "54.4100",
    "y": "32.6400"
  },
  {
    "asset_code": "RM62",
    "asset_name": "CM1-RM62",
    "holder": "RM62",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1รับวัตถุดิบ",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "90.0100",
    "y": "20.3200"
  },
  {
    "asset_code": "PA31",
    "asset_name": "CM1-PA31",
    "holder": "PA31",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.2800",
    "y": "46.2200"
  },
  {
    "asset_code": "N3C302",
    "asset_name": "select_line2",
    "holder": "สายพาน ไลน์ 2",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "DS-2CD3021G0-I",
    "serial": "I20231211AAWRAX8234257",
    "department": "2ผลิต",
    "ip": "192.168.20.50",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "66.4000",
    "y": "30.0400"
  },
  {
    "asset_code": "PA29",
    "asset_name": "CM1-PA29",
    "holder": "PA29",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "1แพคกิ้ง",
    "ip": "",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "13",
    "x": "38.2200",
    "y": "51.4900"
  },
  {
    "asset_code": "N4C2202",
    "asset_name": "fn_dry",
    "holder": "ลิฟท์ F/n Dry",
    "type": "Camera",
    "brand": "Hikvision",
    "model": "",
    "serial": "",
    "department": "2สโตร์ฯ",
    "ip": "192.168.20.98",
    "mac_address": "",
    "status": "Active",
    "image": "",
    "map_id": "1",
    "x": "47.9200",
    "y": "34.3800"
  }
],
  department: [
  {
    "department": "2ผลิต"
  },
  {
    "department": "1เครื่องกล"
  },
  {
    "department": "2สโตร์ฯ"
  },
  {
    "department": "2บุคคลฯ"
  },
  {
    "department": "2ห้องปฏิบัติการ"
  },
  {
    "department": "1แพคกิ้ง"
  },
  {
    "department": "2รับวัตถุดิบ"
  },
  {
    "department": "1รับวัตถุดิบ"
  },
  {
    "department": "1ผลิต"
  },
  {
    "department": "1สโตร์ฯ"
  },
  {
    "department": "1เทคโนโลยีสารสนเทศ"
  },
  {
    "department": "2แพคกิ้ง"
  },
  {
    "department": "1บุคคลฯ"
  },
  {
    "department": "2เครื่องกล"
  },
  {
    "department": "2เทคโนโลยีสารสนเทศ"
  },
  {
    "department": "2สิ่งแวดล้อม"
  }
],
  map: [
  {
    "map_id": "1",
    "map_name": "CM2 ชั้น 1",
    "map_pic": ""
  },
  {
    "map_id": "4",
    "map_name": "CM2 ชั้น 2",
    "map_pic": ""
  },
  {
    "map_id": "13",
    "map_name": "CM1",
    "map_pic": ""
  }
],
  user: [
  {
    "Name": "admin",
    "password": "cmfsupport",
    "department": "admin",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "it2",
    "password": "Cmf123456",
    "department": "2บุคคลฯ,2ผลิต,2รับวัตถุดิบ,2สิ่งแวดล้อม,2สโตร์ฯ,2ห้องปฏิบัติการ,2เครื่องกล,2เทคโนโลยีสารสนเทศ,2แพคกิ้ง",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "it1",
    "password": "Cmf123456",
    "department": "1บุคคลฯ,1ผลิต,1รับวัตถุดิบ,1สโตร์ฯ,1เครื่องกล,1เทคโนโลยีสารสนเทศ,1แพคกิ้ง",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "pa2",
    "password": "1234",
    "department": "2แพคกิ้ง",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "st2",
    "password": "1234",
    "department": "2สโตร์ฯ",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "pa1",
    "password": "1234",
    "department": "1แพคกิ้ง",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "ec2",
    "password": "ec1234",
    "department": "2ผลิต,2สโตร์ฯ,2รับวัตถุดิบ,2แพคกิ้ง,2เครื่องกล",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "pr2",
    "password": "1234",
    "department": "2ผลิต",
    "camera_user": "",
    "map_user": ""
  },
  {
    "Name": "hr2",
    "password": "1234",
    "department": "2บุคคลฯ",
    "camera_user": "",
    "map_user": ""
  }
]
};
